---
title: "Untitled"
output: html_document
author: Geetha Perera
date: 8/4/2020
---

# Title

create some **bold** text or in _italics_.

```
a block code
```

* bold with doulbe asterisks 
* italics with underscores
* code with three backticks

1. bold with doulbe asterisks 
2. italics with underscores
3. code with three backticks

## 2nd level header
```{r,echo=FALSE}
library(tidyverse)

gapminder <- read_csv("data/gapminder_data.csv")
gapminder
aus_data <- filter(gapminder, country=="Australia")
ggplot(aus_data, aes(x=year, y=pop))+geom_line()
```

### 3rd level header

Write some paragrahs


```{r}
aus_data <- filter(gapminder, country=="Australia")
ggplot(aus_data, aes(x=year, y=pop))+geom_line()
```

write more texts

```{r,eval=gapminder}
library(tidyverse)

gapminder <- read_csv("data/gapminder_data.csv")
gapminder

```

```{r}
library(tidyverse)

gapminder <- read_csv("data/gapminder_data.csv")
gapminder
aus_data <- filter(gapminder, country=="Australia")
```

```{r}
library(tidyverse)

gapminder <- read_csv("data/gapminder_data.csv")
gapminder
aus_data <- filter(gapminder, country=="Australia")
ggplot(aus_data, aes(x=year, y=pop))+geom_line()
```

